### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by upadhay454** [gaurangparmar89/BigData#1]
some file are missing in this pl analysis project like keyword_extract_31.txt  , final_count_31_SRH.txt  , descorder_extract_31.txt

**Comment by gaurangparmar89** [comment]
Those are output files for different classes.
1) descorder_extract file is generated after running the GetMostKeywords class which will list the words in desc order of count.
2) keyword_extract file is generated after running the StopWord class which takes the Step1 file as input and removes stopwords such as (to, and etc.)
- final_count file is generated after running the Analysis class which takes the Step2 file as input and gives the final count.

**Comment by upadhay454** [comment]
Thanks for your reply. But I am still getting some problem, can you please help me more. And also topsy is shutted down so should i have to change this or would it difficulty to remove. New api http://support.chartbeat.com/docs/api.html#live
![screenshot 369](https://cloud.githubusercontent.com/assets/13587532/24370483/2f8a2f76-1345-11e7-984c-466e0e34f88b.png)
![screenshot 370](https://cloud.githubusercontent.com/assets/13587532/24370484/2f8cc6f0-1345-11e7-9551-6e39124cf759.png)
 I am getting problem while running the code.
